### ISSUE TITLE
Error on container startup

### ISSUE THREAD

**Issue by kssxs** [petersem/monocker#100]
Hi there,

I'm seeing the following issue when the container starts:

![image](https://github.com/user-attachments/assets/0438894d-8b59-4881-8693-9ff82f08845c)

Any idea what might be going on here?

Thanks in advance!

**Comment by kssxs** [comment]
Seems it was a misconfiguration on my part.  Removed the DOCKER_HOST environment variable (I thought I had to define it in case it wasn't 'default'), and to make sure, I bound the volume /var/run/docker.sock (don't know if I needed that), and then it worked without error.

Leaving this here in case it helps anyone, but of course you're free to delete the post as well :) .

**Comment by petersem** [comment]
Thanks, I should add better error handling. You are correct in your assumption. You must have either a binding for docker.sock or a valid docker_socket value.
