### ISSUE TITLE
Add a line break in the telegram message between title and message

### ISSUE THREAD

**Issue by thelpfy** [petersem/monocker#109]
Hey, thanks for this awesome project, it is really helpful in monitoring when there is problem with a container.

I didn't want to create a PR for this simple fix, so could you please add a `<br>` between the title and message in the telegram message?

Because currently it looks like this:

> MONOCKER (-.-)ghostfolio: running (healthy)
> jellyfin: running \
> radarr: running \
> lidarr: running

So if you could add this in your next update, that would be great :)

**Comment by petersem** [comment]
@thelpfy Fixed in latest version 2.13.6. 
![image](https://github.com/user-attachments/assets/c0d963f7-5834-452c-9e28-00b8c0299b73)
