### ISSUE TITLE
Is it possible to distinguish between labels for different monocker instances? 

### ISSUE THREAD

**Issue by eugeneyng** [petersem/monocker#110]
Scenario I have: 

I have two Discord servers that are tracking different gameservers, each running in its own docker container. In both containers, the LABEL_ENABLE flag is true and I have the monocker.enable set to true.

Both Discord servers then get notifications for both containers because the label is the same. Is it possible to label them in such a way so that each Discord server only gets monitoring messages for its own docker container?

**Comment by petersem** [comment]
I'm not quite sure i follow you. Are you saying that you are running two monocker containers on the same host machine, both monitoring containers on the same machine? Then you are wanting each instance of monocker to only monitor discrete containers?

If so, monocker only supports:
- all containers on a host
- or ones with labels
It doesn't monitor at a more specific level

**Comment by eugeneyng** [comment]
That's correct, sorry for the confusion.

And thank you for the clarification!
