### ISSUE TITLE
document which docker permissions are required

### ISSUE THREAD

**Issue by rpatel3001** [petersem/monocker#20]
Hello,

Which docker permissions are required to use this container? I'm wary of giving containers unrestricted access to the docker socket and would like to expose it via docker-socket-proxy and the DOCKER_HOST environment variable with limited permissions.

**Comment by rpatel3001** [comment]
This container does not yet support DOCKER_HOST, but once it does it only requires `GET` request permissions on the `/containers` endpoint

**Comment by petersem** [comment]
Will locket at using docker socket soon
