### ISSUE TITLE
[FEATURE REQUEST] Add notifications to matrix

### ISSUE THREAD

**Issue by MartenBE** [petersem/monocker#34]
The matrix protocol is an up and coming chat software in the open source world. I was wondering if support for sending notifications to a Matrix room could be implemented?

**Comment by petersem** [comment]
Not heard of it, but will investigate

**Comment by petersem** [comment]
@MartenBE i'll install self_hosted appraise, then try out an matrix package on npm. Looks pretty simple.

**Comment by petersem** [comment]
Working in Dev, but I'm not overly happy with the options available for how messages look. 
![image](https://github.com/petersem/monocker/assets/1418289/b6f81db0-d0bf-4310-8055-723d18fffe96)

**Comment by petersem** [comment]
> @MartenBE i'll install self_hosted appraise, then try out a matrix package on npm. Looks pretty simple.

I went to install a docker version of apraise, but it's a lesson in **_not_** how to deploy a containerise app. As soon as they want to to manually run commands to create things like db users, i just feel like they are to lazy to build this in from readin env variables. </end-rant> :)

**Comment by petersem** [comment]
@MartenBE I'll probably release the Matrix integration later today

**Comment by MartenBE** [comment]
It's been quite a while since I looked at this, but I'll try it out when released :)

**Comment by petersem** [comment]
This is released now. Please note that when you enter the user id in the compose.yaml, do it without the leading @ character. I use @ as a delimeter for parameters. My code will sort out the missing @ from the user id
