### ISSUE TITLE
Feature request: support ntfy as provider

### ISSUE THREAD

**Issue by ksurl** [petersem/monocker#39]
[ntfy.sh](https://ntfy.sh) is a simple notification service that can be selfhosted or using the dev's own cloud instance.

Is the current code using a framework like apprise to simplify adding services? Shoutrrr is another option that uses apprise under the hood I think.

**Comment by lerra** [comment]
+1 on ntfy :)

**Comment by rubenixnagios** [comment]
second this!!

**Comment by ksurl** [comment]
can be closed if no new features being added
