### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by g0sy** [petersem/monocker#57]
Hey, great project! I don't know if this is the place to ask this but, would you mind explaning a bit further about " # MESSAGE_PLATFORM: 'discord@webhook_url' " ? Creating a simple webhook from a discord channel doesn't work.

Thanks in advance.

**Comment by bjornclauw** [comment]
example string for `docker-compose.yml`. Leave the # as this is to comment out a value in this file. Insert the webhook URL like below.
```docker
environment:
  ...
  MESSAGE_PLATFORM: 'discord@https://discord.com/api/webhooks/1234567/1gg6sqfg1bsdgb1-gsdfg54s6d_jKyv_4gs6dfg5s4dfAs2fV54EF54fserf86E'
  ...
```

**Comment by g0sy** [comment]
Thank you for the quick reply. Worked now!

**Comment by petersem** [comment]
Thanks
