### ISSUE TITLE
LABEL_ENABLE / monocker.enable Not Working

### ISSUE THREAD

**Issue by jimmybrancaccio** [petersem/monocker#67]
I've added the label `monocker.enable=false` to two containers however I am still getting notifications regarding them. I have not manually set the `LABEL_ENABLE` environment variable so it should be defaulting to `false`.

Of note I am using Docker Swarm so I am not sure if this makes a difference. If any other information is needed to troubleshoot this please don't hesitate to ask 😄

**Comment by tamimology** [comment]
I believe you should include the `LABEL_ENABLE: 'true'` in the monocker environment variable as it includes/excludes the labeled/not labeled containers. Otherwise, if set to false as defaulted, then all containers will be monitored regardless of their labelling

![image](https://github.com/petersem/monocker/assets/90429593/388332d6-8d61-44e3-a808-b333b95b4715)

**Comment by petersem** [comment]
> I believe you should include the `LABEL_ENABLE: 'true'` in the monocker environment variable as it includes/excludes the labeled/not labeled containers. Otherwise, if set to false as defaulted, then all containers will be monitored regardless of their labelling
> 
> ![image](https://private-user-images.githubusercontent.com/90429593/277930947-388332d6-8d61-44e3-a808-b333b95b4715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Mjc0OTksIm5iZiI6MTcxNTYyNzE5OSwicGF0aCI6Ii85MDQyOTU5My8yNzc5MzA5NDctMzg4MzMyZDYtOGQ2MS00NGUzLWE4MDgtYjMzM2I5NWI0NzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE5MDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZWEwODAyZGEzZjYyZWNlMWQ4OTVjOTkxYjNkZGU0OTdiNDIzNzY1ODEzODI0NGNlNTBjMGE2YTU1N2FhNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NTY4PQpaVfJ8Jnd3upXJ8FUX9sD-yxLja665naxOwQE)

Yes, you have to enable labels in the minocker container before it looks for them in other containers.
