### ISSUE TITLE
Releases section

### ISSUE THREAD

**Issue by jehy** [petersem/monocker#72]
Hi! Thanks for the great tool!
I noticed through monocker that there was a recent release of docker image, and it would be great to see what exactly was in that release. Could you make a release section with release notes? And may be auto build docker image in github CI with releases :)

Happy new Year!

**Comment by petersem** [comment]
I'll have a look. Monocker is stable, so any changes are generally output formatting.

**Comment by petersem** [comment]
For now, any commits will be echoed in the releases section on discord. I generally discuss any updates there as well.
