### ISSUE TITLE
Notification title

### ISSUE THREAD

**Issue by tamimology** [petersem/monocker#73]
It would be useful to have an option to specify the notification title for each one sent to the assigned platform. Currently, it is set to "MONOCKER", if there is an env variable to override it then it would be terrific.

For example. I have 2 monocker running, one on my synology and another on my mini pc. I share the same docker-compose file and use the same pushover API. It would be nice to have a title specified for one as "MONOCKER - SYNOLOGY" and another "MONOCKER - MINI-PC" for example so I can know which host is having this notification/issue or whatever it is.

**Comment by petersem** [comment]
There is a 'SERVER_LABEL' option to do this now.
![Screenshot_20240513_134412_Discord](https://github.com/petersem/monocker/assets/1418289/9962b2d7-04de-4dbb-bf26-67c2dc51d291)
