### ISSUE TITLE
status messages in wrong order

### ISSUE THREAD

**Issue by cusooner** [petersem/monocker#8]
I am letting my containers auto-update via ouroboros. Status messages are sent via telegram.
Status appears in the wrong order in the telegram feed. See screenshot attached.

![Screenshot 2021-10-08 125138](https://user-images.githubusercontent.com/43494413/136544544-1fc24739-de4e-47fb-b154-d36e9bb6f843.png)

**Comment by petersem** [comment]
Ouroboros has been deprecated for some time now. Suggest you move to watchtower. 

Depending upon your configure options, im not sure about this. Ouroboros and watchtower both do some funky stuff with renaming containers, so id have to have a closer look. How have you configured monocker?

**Comment by petersem** [comment]
It's alabout detecting state changes between 10 second polls. If the state changes more than once between polls, then the initial change wont be detected. So it could apear that state changes are out of oprder. Ultimately, it is what it is. :) 

Monocker is not designed to do what Ouroboros or watchtower does. It does not detect updated images. It detects when the state of container changes. For example, I want to know if a container crashes, or crashes and restarts.

**Comment by yubiuser** [comment]
@cusooner 

as petersem pointed out the "long" polling time of 10 seconds is the issue here. As this is a hard-coded limit, I created a fork at ghcr.io/yubiuser/yubiuser/monocker:latest without the limit. You can set `PERIOD:` as small as you want. However, faster polling times will increase your load significantly.
