### ISSUE TITLE
Update docs to include links to API documentation

### ISSUE THREAD

**Issue by Figrol** [petersem/monocker#83]
Please can you include a link in the docs where you say "For Telegram: See documentation for how to obtain ID values" I have no clue whether you are talking about docs you have written or Telegram docs?

**Comment by petersem** [comment]
Good idea. It's not a simple process for telegram though. I'll update the doco with links when i can.

**Comment by petersem** [comment]
@Figrol  i added some image for other api data, and also a for telegram, i did a video. Link in readme
