### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by BendRicks** [petersem/monocker#97]
Is it possible to use monocker behind proxy? I tried setting env variables inside docker compose but it didn't work, it refuses connection to api servers

**Comment by petersem** [comment]
Could you please elaborate on a use case for this please?

**Comment by BendRicks** [comment]
I tried to set up monocker on corporate server behind proxy, and it was not able to send messages to discord or telegram, even though http_proxy environment variable was configured and ordinary curl requests inside container worked fine. Unfortunately, I already wrote a similar tool myself and changed my working PC, so I don't have screenshots or browser history to look for what errors were produced.

**Comment by BendRicks** [comment]
I tried to look at source code and I think that monocker uses methods that just ignore proxy settings

**Comment by petersem** [comment]
@BendRicks so monocker works, but calls to a specific message endpoint doesn't?

**Comment by BendRicks** [comment]
Monocker sees container health changes, but not able to send requests to telegram and discord API. And yes, I tried configuring docker client, that didn't work.

**Comment by petersem** [comment]
@BendRicks I've been investigating this issue, however I have had no luck in replicating it. Unfortunately, I believe it is something unique to your environment. Effectively, messages are all basically https posts, and should just work. 

Unfortunately, I think this is one for the cannot resolve box. If you do find a solution or have further thoughts, then please reach out.
