### ISSUE TITLE
Logo in svg format for Monocker

### ISSUE THREAD

**Issue by IoSonoPiero** [petersem/monocker#99]
Hello, I'd like a logo (possibly) in SVG to use on my Homepage Dashboard.
I've tried to create it, but the results are not good.

I know there is a PNG with the "M", but I don't know why I can't use it in Homepage Dashboard.
That's all!

**Comment by jeffreyswiggins** [comment]
So this is the one I use in Homepage Dashboard for Monocker.  It is not specifically for it, but I liked it and the app it was for is one I will never use.

https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/metabase.png

![image](https://github.com/user-attachments/assets/b9af3cc3-e87c-4e64-b634-8e40085f07e6)


There is a cache of icons you can “pull links” from at:
https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md

**Comment by petersem** [comment]
Sorry, i have the graphical abilities of a 2 year old. ;) Just find something you like on the web and use that.
